name: Create Heatmap

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Google Fonts
        run: sh download.sh

      - name: Install project dependencies
        run: uv sync --frozen --no-dev

      - name: Create heatmap
        run: uv run main.py

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        environment:
          name: github-pages
