from collections.abc import Iterable, Sequence
from pathlib import Path

import numpy as np

type PathLike = Path | str

def glyph_outline_coordinates(font_paths: Sequence[PathLike]) -> np.ndarray: ...
def units_per_em(font_paths: Iterable[PathLike]) -> list[int]: ...
def glyph_command_counts(font_paths: Iterable[PathLike]) -> list[int]: ...
def coverage_bmp(font_paths: Iterable[PathLike], limit: int) -> list[list[int]]: ...
